name: Add contributors
on:
  schedule:
    - cron:  '20 20 * * *'

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: BobAnkh/add-contributors@master
      with:
        REPO_NAME: 'krishrahul98/DSA-Library'
        CONTRIBUTOR: '### Contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/CONTRIBUTORS.md'
        COMMIT_MESSAGE: 'Update Contributors'
        AVATAR_SHAPE: 'round'
